### ISSUE TITLE
Sérieux, textures sous Blender ? 

### ISSUE THREAD

**Issue by Salamandar** [robotronik/cdfr2017-simulation-table#1]

**Comment by kaeipnos** [comment]
vas dormir.

**Comment by Salamandar** [comment]
Je rentre de concert, ce qui n'est probablement pas ton cas.

**Comment by kaeipnos** [comment]
eh ouais FreeCAD n'a pas ça intégré.
En même temps de l'UV mapping dans un outils de CAO je trouverais ça bizarre.

**Comment by Salamandar** [comment]
Non mais c'est surtout que ça servira à quoi ?

**Comment by kaeipnos** [comment]
Mhh à première vue:
- voir si freecad peut convenir pour le club
- vérifier que les dessins de plasci sont corrects (spoil : ils ne le sont pas)
- en modéliant un robot "boîte" dans les périmètres statique et dynamique, voir quel design est possible pour gagner potentiellement le maximum de points avec le maximum de fiablilité
- simuler l'asser et un peu de strat sous gazebo, mettre en pratique ros
- paralléliser la méca et le soft du robot

**Comment by Salamandar** [comment]
Non c'est surtout la partie "Textures sous Blender" qui me dérange. À part à s'amuser (et c'est pas rien, certes), ça servira à quoi ?

**Comment by Salamandar** [comment]
Non c'est surtout la partie "Textures sous Blender" qui me dérange. À part à s'amuser (et c'est pas rien, certes), ça servira à quoi ?

**Comment by kaeipnos** [comment]
ça permet de repérer plus facilement les objets, ce serait moins facile si tout était gris; il faudra bien texturer les modules bicolores par exemple.
Et puis, si on a le temps et l'utilité, faire de la reconnaissance visuelle.

J'ai mis le .blend pour montrer comment on peut faire ça avec blender, ça aurait été dommage je trouve de ne fournir que les fichiers 3D .dae.

Texturer un objet est souvent bien moins long que créer l'objet, ce serait dommage de s'en priver.
